### PR TITLE
Register special route with publishing api

### PR DESCRIPTION
**Pull request by heathd**
we've introduced a new special_route format[1] to allow us to register
unusual routes which don't have a real format associated with them. This
supersedes the previous approach of registering such routes via the
router. The advantage of registering with publishing api is that the
routes will also be reserved with url-arbiter which should eliminate the
risk of clashes.

This adds a rake task to register the `/api` prefix route via that
mechanism, and removes the old method of registering directly with the
router.

The intention is to run this rake task on deploy (as we do for the route
registration at present).

[1] alphagov/govuk-content-schemas#106

### CODE REVIEW

**Comment by elliotcm** [comment]
Is this comment still relevant?

https://github.com/alphagov/govuk_content_api/pull/224/files#diff-6a93c0cd658774d3b7c3f2a081ba8166L30

**Comment by heathd** [comment]
I think that "Register public api proxy and routes with the router" is covered by the title and description of the route.

I think "(run this task on server in cluster)" is fairly self-evident but I'm open to the possibility that it may not be to others. 

What do you think?

**Comment by alext** [comment]
I think the code is good as it stands.  I agree that the comment is now unnecessary.

**Comment by elliotcm** [comment]
It's not very useful as-is (any server? which cluster?) so we can probably take it out.

**Pull request merged**
