### PR TITLE
Remove /artefact.json endpoint from content-api

### PR DESCRIPTION
**Pull request by Davidslv**
Trello:
https://trello.com/c/TG7hX7ms/151-remove-artefact-json-endpoint-from-content-api

paired with @theKHutDeveloper

### CODE REVIEW

**Comment by alecgibson** [comment]
There's a lot of other `410` endpoints still hanging around - are we sure we're meant to remove this endpoint?

**Comment by carvil** [comment]
It's ok to remove as this is not being used anymore. We will be shutting down the API in the next couple of weeks.

**Comment by tijmenb** [comment]
Not sure if it's clear, but this PR removes `/artefacts.json`, not `/artefact.json` as it says in the commit/description & trello ticket.

**Comment by carvil** [comment]
@tijmenb that was a mistake in the Trello card and on the title of the PR. The task was to remove `artefacts` and not the `artefact` endpoint, as it's still being used. We are chasing that now before we turn it off. Thanks for mentioning!

**Pull request merged**
